name = "woofyworkers-proxy"
main = "index.js"
compatibility_date = "2024-08-02"

[vars]
GSCRIPT_ENQUIRY_URL = "https://script.google.com/macros/s/AKfycbygOvUK4Wd8feJ1_4HBnkfijRnad_tk-uhou2wNIMEKOMy7yrVsP_B4KfIU9GBYidXX/exec"
GSCRIPT_PURCHASE_URL = "https://script.google.com/macros/s/AKfycbygOvUK4Wd8feJ1_4HBnkfijRnad_tk-uhou2wNIMEKOMy7yrVsP_B4KfIU9GBYidXX/exec" # Use the same or new Apps Script endpoint if different
